### ISSUE TITLE
Idiot question (skid warning!)

### ISSUE THREAD

**Issue by pazza2234** [chromebook-guide/chromebook-guide.github.io#1]
dose using recomod, not tethering but just recomod make my chromebook not able to boot normaly?
extra info, dev mode, no rootfs verifacation, and murkmodded. I want to use recomod's other features.

also what happens if you fail pressing E on boot?

**Comment by rainestorme** [comment]
No, it shouldn't prevent you from using your Chromebook normally. If you fail to press E on boot, then RecoMod will work fine, just not allow you to boot E-Halcyon. I won't get into the technical details but you should really read [the writeup](https://coolelectronics.me/blog/breaking-cros-5) for more info.
