### ISSUE TITLE
Needed: KVS page

### ISSUE THREAD

**Issue by ahinojos0029** [chromebook-guide/chromebook-guide.github.io#6]
KVS page needed. Please add it as soon as possible.

If you guys need some help, I can be of assistance. Just shoot me a DM on discord: @atmoglaa

**Comment by ABadGame** [comment]
Closing issue as I have decided to fork it and make my own guide.

**Comment by rainestorme** [comment]
> Closing issue as I have decided to fork it and make my own guide.

Upstream contribution is always welcome.
